print("+-------------------------------------------------------------+")
print("| 1 |     english III                     |   Ms.Lapan        |")
print("| 2 |     Precalculus                     |   Mrs.Gideon      |")
print("| 3 |     Music Theory                    |   Mr.Davis        |")
print("| 4 |   Biotechnology                     |   Ms.Palmer       |")
print("| 5 |principles of Technolog              | MS.Garcia         |")
print("| 6 |          Latin II                   |   Mrs.Barnett     |")
print("| 7 |     AP US History                   |   Ms.Johannessen  |")
print("| 8 |Business Computer Information Systems|   Mr.James        |")
print("+-------------------------------------------------------------+")
