print("Please enter the following information so i can sell it for a profit!")
f_name=input("first name:")

l_name=input("last name:")
grade=int(input("Grade (9-12):"))
id=int(input("student ID:"))
login=input("login:")
gpa=float(input("GPA (0.0-4.0):"))
print("\n")
print("your information:")
print("login:",login)
print("ID:",id)
print("name:",f_name+l_name)
print("GPA:",gpa)
print("Grade:",grade)
